# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getXML1 <- function(str, child) {
    .Call(`_openxlsx_getXML1`, str, child)
}

getXML1val <- function(str, child) {
    .Call(`_openxlsx_getXML1val`, str, child)
}

getXML2 <- function(str, level1, child) {
    .Call(`_openxlsx_getXML2`, str, level1, child)
}

getXML2val <- function(str, level1, child) {
    .Call(`_openxlsx_getXML2val`, str, level1, child)
}

getXML3 <- function(str, level1, level2, child) {
    .Call(`_openxlsx_getXML3`, str, level1, level2, child)
}

getXML3value <- function(str, level1, level2, child) {
    .Call(`_openxlsx_getXML3value`, str, level1, level2, child)
}

getXMLattr <- function(strs, child) {
    .Call(`_openxlsx_getXMLattr`, strs, child)
}

getXML1attr_one <- function(str, child, attr) {
    .Call(`_openxlsx_getXML1attr_one`, str, child, attr)
}

calc_column_widths <- function(sheet_data, sharedStrings, autoColumns, widths, baseFontCharWidth, minW, maxW) {
    .Call(`_openxlsx_calc_column_widths`, sheet_data, sharedStrings, autoColumns, widths, baseFontCharWidth, minW, maxW)
}

convert_to_excel_ref <- function(cols, LETTERS) {
    .Call(`_openxlsx_convert_to_excel_ref`, cols, LETTERS)
}

convert_from_excel_ref <- function(x) {
    .Call(`_openxlsx_convert_from_excel_ref`, x)
}

convert_to_excel_ref_expand <- function(cols, LETTERS, rows) {
    .Call(`_openxlsx_convert_to_excel_ref_expand`, cols, LETTERS, rows)
}

isInternalHyperlink <- function(x) {
    .Call(`_openxlsx_isInternalHyperlink`, x)
}

write_file <- function(head = "", body = "", tail = "", fl = "") {
    .Call(`_openxlsx_write_file`, head, body, tail, fl)
}

cppReadFile <- function(xmlFile) {
    .Call(`_openxlsx_cppReadFile`, xmlFile)
}

read_file_newline <- function(xmlFile) {
    .Call(`_openxlsx_read_file_newline`, xmlFile)
}

get_letters <- function() {
    .Call(`_openxlsx_get_letters`)
}

markUTF8 <- function(x, clone) {
    .Call(`_openxlsx_markUTF8`, x, clone)
}

getNodes <- function(xml, tagIn) {
    .Call(`_openxlsx_getNodes`, xml, tagIn)
}

getOpenClosedNode <- function(xml, open_tag, close_tag) {
    .Call(`_openxlsx_getOpenClosedNode`, xml, open_tag, close_tag)
}

getAttr <- function(x, tag) {
    .Call(`_openxlsx_getAttr`, x, tag)
}

getChildlessNode_ss <- function(xml, tag) {
    .Call(`_openxlsx_getChildlessNode_ss`, xml, tag)
}

getChildlessNode <- function(xml, tag) {
    .Call(`_openxlsx_getChildlessNode`, xml, tag)
}

get_extLst_Major <- function(xml) {
    .Call(`_openxlsx_get_extLst_Major`, xml)
}

cell_ref_to_col <- function(x) {
    .Call(`_openxlsx_cell_ref_to_col`, x)
}

int_2_cell_ref <- function(cols) {
    .Call(`_openxlsx_int_2_cell_ref`, cols)
}

readXMLPtr <- function(path) {
    .Call(`_openxlsx_readXMLPtr`, path)
}

getXMLXPtr1 <- function(doc, child) {
    .Call(`_openxlsx_getXMLXPtr1`, doc, child)
}

getXMLXPtr2 <- function(doc, level1, child) {
    .Call(`_openxlsx_getXMLXPtr2`, doc, level1, child)
}

getXMLXPtr3 <- function(doc, level1, level2, child) {
    .Call(`_openxlsx_getXMLXPtr3`, doc, level1, level2, child)
}

getXMLXPtr4 <- function(doc, level1, level2, level3, child) {
    .Call(`_openxlsx_getXMLXPtr4`, doc, level1, level2, level3, child)
}

getXMLXPtr5 <- function(doc, level1, level2, level3, level4, child) {
    .Call(`_openxlsx_getXMLXPtr5`, doc, level1, level2, level3, level4, child)
}

getXMLXPtr2val <- function(doc, level1, child) {
    .Call(`_openxlsx_getXMLXPtr2val`, doc, level1, child)
}

getXMLXPtr3val <- function(doc, level1, level2, child) {
    .Call(`_openxlsx_getXMLXPtr3val`, doc, level1, level2, child)
}

getXMLXPtr4val <- function(doc, level1, level2, level3, child) {
    .Call(`_openxlsx_getXMLXPtr4val`, doc, level1, level2, level3, child)
}

getXMLXPtr5val <- function(doc, level1, level2, level3, level4, child) {
    .Call(`_openxlsx_getXMLXPtr5val`, doc, level1, level2, level3, level4, child)
}

loadvals <- function(wb, doc) {
    invisible(.Call(`_openxlsx_loadvals`, wb, doc))
}

getXMLXPtr1attr <- function(doc, child) {
    .Call(`_openxlsx_getXMLXPtr1attr`, doc, child)
}

getXMLXPtr2attr <- function(doc, level1, child) {
    .Call(`_openxlsx_getXMLXPtr2attr`, doc, level1, child)
}

getXMLXPtr3attr <- function(doc, level1, level2, child) {
    .Call(`_openxlsx_getXMLXPtr3attr`, doc, level1, level2, child)
}

getXMLXPtr4attr <- function(doc, level1, level2, level3, child) {
    .Call(`_openxlsx_getXMLXPtr4attr`, doc, level1, level2, level3, child)
}

getXMLXPtr5attr <- function(doc, level1, level2, level3, level4, child) {
    .Call(`_openxlsx_getXMLXPtr5attr`, doc, level1, level2, level3, level4, child)
}

getXMLXPtr1attr_one <- function(doc, child, attrname) {
    .Call(`_openxlsx_getXMLXPtr1attr_one`, doc, child, attrname)
}

getXMLXPtr2attr_one <- function(doc, level1, child, attrname) {
    .Call(`_openxlsx_getXMLXPtr2attr_one`, doc, level1, child, attrname)
}

getXMLXPtr3attr_one <- function(doc, level1, level2, child, attrname) {
    .Call(`_openxlsx_getXMLXPtr3attr_one`, doc, level1, level2, child, attrname)
}

getXMLXPtr4attr_one <- function(doc, level1, level2, level3, child, attrname) {
    .Call(`_openxlsx_getXMLXPtr4attr_one`, doc, level1, level2, level3, child, attrname)
}

printXPtr <- function(doc, raw) {
    .Call(`_openxlsx_printXPtr`, doc, raw)
}

readXML <- function(path) {
    .Call(`_openxlsx_readXML`, path)
}

get_shared_strings <- function(xmlFile, isFile) {
    .Call(`_openxlsx_get_shared_strings`, xmlFile, isFile)
}

getCellInfo <- function(xmlFile, sharedStrings, skipEmptyRows, startRow, rows, getDates) {
    .Call(`_openxlsx_getCellInfo`, xmlFile, sharedStrings, skipEmptyRows, startRow, rows, getDates)
}

read_workbook <- function(cols_in, rows_in, v, string_inds, is_date, hasColNames, hasSepNames, skipEmptyRows, skipEmptyCols, nRows, clean_names) {
    .Call(`_openxlsx_read_workbook`, cols_in, rows_in, v, string_inds, is_date, hasColNames, hasSepNames, skipEmptyRows, skipEmptyCols, nRows, clean_names)
}

calc_number_rows <- function(x, skipEmptyRows) {
    .Call(`_openxlsx_calc_number_rows`, x, skipEmptyRows)
}

set_row <- function(row_attr, cells) {
    .Call(`_openxlsx_set_row`, row_attr, cells)
}

set_sst <- function(sharedStrings) {
    .Call(`_openxlsx_set_sst`, sharedStrings)
}

list_to_attr <- function(attributes, node) {
    .Call(`_openxlsx_list_to_attr`, attributes, node)
}

list_to_attr_full <- function(attributes, node, child) {
    .Call(`_openxlsx_list_to_attr_full`, attributes, node, child)
}

map_cell_types_to_integer <- function(t) {
    .Call(`_openxlsx_map_cell_types_to_integer`, t)
}

map_cell_types_to_char <- function(t) {
    .Call(`_openxlsx_map_cell_types_to_char`, t)
}

build_cell_types_integer <- function(classes, n_rows) {
    .Call(`_openxlsx_build_cell_types_integer`, classes, n_rows)
}

buildCellTypes <- function(classes, nRows) {
    .Call(`_openxlsx_buildCellTypes`, classes, nRows)
}

build_cell_merges <- function(comps) {
    .Call(`_openxlsx_build_cell_merges`, comps)
}

buildCellList <- function(r, t, v) {
    .Call(`_openxlsx_buildCellList`, r, t, v)
}

#' @import Rcpp
write_worksheet_xml_2 <- function(prior, post, sheet_data, cols_attr, rows_attr, row_heights_ = NULL, outline_levels_ = NULL, R_fileName = "output") {
    .Call(`_openxlsx_write_worksheet_xml_2`, prior, post, sheet_data, cols_attr, rows_attr, row_heights_, outline_levels_, R_fileName)
}

buildMatrixNumeric <- function(v, rowInd, colInd, colNames, nRows, nCols) {
    .Call(`_openxlsx_buildMatrixNumeric`, v, rowInd, colInd, colNames, nRows, nCols)
}

buildMatrixMixed <- function(v, rowInd, colInd, colNames, nRows, nCols, charCols, dateCols) {
    .Call(`_openxlsx_buildMatrixMixed`, v, rowInd, colInd, colNames, nRows, nCols, charCols, dateCols)
}

matrixRowInds <- function(indices) {
    .Call(`_openxlsx_matrixRowInds`, indices)
}

build_table_xml <- function(table, tableStyleXML, ref, colNames, showColNames, withFilter) {
    .Call(`_openxlsx_build_table_xml`, table, tableStyleXML, ref, colNames, showColNames, withFilter)
}

